version: 2.1
jobs:
  one:
    docker:
      - image: circleci/node:12.18.0
    steps:
      - checkout
      - run:
          name: update-npm
          command: 'sudo npm install -g npm@latest'
      - restore_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
      - run:
          name: install-npm-wee
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
          paths:
            - ./node_modules
      - run:
          name: test
          command: ./node_modules/.bin/nyc npm test -- --reporter mocha-junit-reporter --reporter-options "mochaFile=./test-results/mocha/test-results.xml"
      - run:
          name: code-coverage
          command: './node_modules/.bin/nyc report --reporter cobertura --report-dir ./coverage'
      - store_artifacts:
          path: test-results
          destination: tests
      - store_artifacts:
          path: coverage
          destination: coverage
      - store_test_results:
          path: test-results
  two:
    docker:
      - image: circleci/ruby:2.4.1
        auth:
          username: mydockerhub-user
          password: $DOCKERHUB_PASSWORD
    steps:
      - checkout
      - run: echo "A more familiar hi"

workflows:
  version: 2.1
  one_and_two:
    jobs:
      - one
      - two
